TD_iPhone[0] = TextDrawCreate(507.000183, 195.792556, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[0], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[0], 16.000000, 16.000000);
TextDrawAlignment(TD_iPhone[0], 1);
TextDrawColor(TD_iPhone[0], -2139062017);
TextDrawSetShadow(TD_iPhone[0], 0);
TextDrawSetOutline(TD_iPhone[0], 0);
TextDrawFont(TD_iPhone[0], 4);

TD_iPhone[1] = TextDrawCreate(506.666839, 404.199951, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[1], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[1], 16.000000, -16.000000);
TextDrawAlignment(TD_iPhone[1], 1);
TextDrawColor(TD_iPhone[1], -2139062017);
TextDrawSetShadow(TD_iPhone[1], 0);
TextDrawSetOutline(TD_iPhone[1], 0);
TextDrawFont(TD_iPhone[1], 4);

TD_iPhone[2] = TextDrawCreate(578.666870, 404.199951, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[2], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[2], 16.000000, -16.000000);
TextDrawAlignment(TD_iPhone[2], 1);
TextDrawColor(TD_iPhone[2], -2139062017);
TextDrawSetShadow(TD_iPhone[2], 0);
TextDrawSetOutline(TD_iPhone[2], 0);
TextDrawFont(TD_iPhone[2], 4);

TD_iPhone[3] = TextDrawCreate(578.666870, 195.792541, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[3], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[3], 16.000000, 16.000000);
TextDrawAlignment(TD_iPhone[3], 1);
TextDrawColor(TD_iPhone[3], -2139062017);
TextDrawSetShadow(TD_iPhone[3], 0);
TextDrawSetOutline(TD_iPhone[3], 0);
TextDrawFont(TD_iPhone[3], 4);

TD_iPhone[4] = TextDrawCreate(507.000061, 202.844375, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[4], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[4], 87.666656, 194.962951);
TextDrawAlignment(TD_iPhone[4], 1);
TextDrawColor(TD_iPhone[4], -2139062017);
TextDrawSetShadow(TD_iPhone[4], 0);
TextDrawSetOutline(TD_iPhone[4], 0);
TextDrawFont(TD_iPhone[4], 4);

TD_iPhone[5] = TextDrawCreate(513.666564, 195.548095, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[5], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[5], 74.666641, 208.651809);
TextDrawAlignment(TD_iPhone[5], 1);
TextDrawColor(TD_iPhone[5], -2139062017);
TextDrawSetShadow(TD_iPhone[5], 0);
TextDrawSetOutline(TD_iPhone[5], 0);
TextDrawFont(TD_iPhone[5], 4);

TD_iPhone[6] = TextDrawCreate(507.333496, 196.377746, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[6], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[6], 16.000000, 16.000000);
TextDrawAlignment(TD_iPhone[6], 1);
TextDrawColor(TD_iPhone[6], 255);
TextDrawSetShadow(TD_iPhone[6], 0);
TextDrawSetOutline(TD_iPhone[6], 0);
TextDrawFont(TD_iPhone[6], 4);

TD_iPhone[7] = TextDrawCreate(507.333496, 403.540649, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[7], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[7], 16.000000, -16.000000);
TextDrawAlignment(TD_iPhone[7], 1);
TextDrawColor(TD_iPhone[7], 255);
TextDrawSetShadow(TD_iPhone[7], 0);
TextDrawSetOutline(TD_iPhone[7], 0);
TextDrawFont(TD_iPhone[7], 4);

TD_iPhone[8] = TextDrawCreate(578.000244, 403.540649, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[8], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[8], 16.000000, -16.000000);
TextDrawAlignment(TD_iPhone[8], 1);
TextDrawColor(TD_iPhone[8], 255);
TextDrawSetShadow(TD_iPhone[8], 0);
TextDrawSetOutline(TD_iPhone[8], 0);
TextDrawFont(TD_iPhone[8], 4);

TD_iPhone[9] = TextDrawCreate(578.000305, 196.377746, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[9], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[9], 16.000000, 16.000000);
TextDrawAlignment(TD_iPhone[9], 1);
TextDrawColor(TD_iPhone[9], 255);
TextDrawSetShadow(TD_iPhone[9], 0);
TextDrawSetOutline(TD_iPhone[9], 0);
TextDrawFont(TD_iPhone[9], 4);

TD_iPhone[10] = TextDrawCreate(514.666809, 196.622222, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[10], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[10], 72.000022, 206.992568);
TextDrawAlignment(TD_iPhone[10], 1);
TextDrawColor(TD_iPhone[10], 255);
TextDrawSetShadow(TD_iPhone[10], 0);
TextDrawSetOutline(TD_iPhone[10], 0);
TextDrawFont(TD_iPhone[10], 4);

TD_iPhone[11] = TextDrawCreate(507.666656, 204.674133, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[11], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[11], 86.333419, 191.229660);
TextDrawAlignment(TD_iPhone[11], 1);
TextDrawColor(TD_iPhone[11], 255);
TextDrawSetShadow(TD_iPhone[11], 0);
TextDrawSetOutline(TD_iPhone[11], 0);
TextDrawFont(TD_iPhone[11], 4);

TD_iPhone[12] = TextDrawCreate(511.333435, 221.925933, "LD_otb:blue");
TextDrawLetterSize(TD_iPhone[12], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[12], 78.666633, 155.140731);
TextDrawAlignment(TD_iPhone[12], 1);
TextDrawColor(TD_iPhone[12], -1768515841);
TextDrawSetShadow(TD_iPhone[12], 0);
TextDrawSetOutline(TD_iPhone[12], 0);
TextDrawFont(TD_iPhone[12], 4);

TD_iPhone[13] = TextDrawCreate(549.666809, 201.599945, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[13], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[13], 3.333292, 4.148138);
TextDrawAlignment(TD_iPhone[13], 1);
TextDrawColor(TD_iPhone[13], -2139062142);
TextDrawSetShadow(TD_iPhone[13], 0);
TextDrawSetOutline(TD_iPhone[13], 0);
TextDrawFont(TD_iPhone[13], 4);

TD_iPhone[14] = TextDrawCreate(544.999877, 209.896240, "ld_poke:cd1d");
TextDrawLetterSize(TD_iPhone[14], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[14], 12.333331, 2.074084);
TextDrawAlignment(TD_iPhone[14], 1);
TextDrawColor(TD_iPhone[14], -2139062142);
TextDrawSetShadow(TD_iPhone[14], 0);
TextDrawSetOutline(TD_iPhone[14], 0);
TextDrawFont(TD_iPhone[14], 4);

TD_iPhone[15] = TextDrawCreate(541.000366, 210.066589, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[15], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[15], 1.333292, 1.244433);
TextDrawAlignment(TD_iPhone[15], 1);
TextDrawColor(TD_iPhone[15], -2139062142);
TextDrawSetShadow(TD_iPhone[15], 0);
TextDrawSetOutline(TD_iPhone[15], 0);
TextDrawFont(TD_iPhone[15], 4);

TD_iPhone[16] = TextDrawCreate(543.333618, 380.311004, "ld_pool:ball");
TextDrawLetterSize(TD_iPhone[16], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[16], 16.333269, 18.251844);
TextDrawAlignment(TD_iPhone[16], 1);
TextDrawColor(TD_iPhone[16], -1061109690);
TextDrawSetShadow(TD_iPhone[16], 0);
TextDrawSetOutline(TD_iPhone[16], 0);
TextDrawFont(TD_iPhone[16], 4);

TD_iPhone[17] = TextDrawCreate(511.333496, 221.925994, "ld_plan:tvbase");
TextDrawLetterSize(TD_iPhone[17], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[17], 78.666702, 9.540740);
TextDrawAlignment(TD_iPhone[17], 1);
TextDrawColor(TD_iPhone[17], -1);
TextDrawSetShadow(TD_iPhone[17], 0);
TextDrawSetOutline(TD_iPhone[17], 0);
TextDrawFont(TD_iPhone[17], 4);

TD_iPhone[18] = TextDrawCreate(550.666687, 221.925918, "4G________________00:00");
TextDrawLetterSize(TD_iPhone[18], 0.194333, 0.865778);
TextDrawAlignment(TD_iPhone[18], 2);
TextDrawColor(TD_iPhone[18], -1);
TextDrawSetShadow(TD_iPhone[18], 0);
TextDrawSetOutline(TD_iPhone[18], 0);
TextDrawBackgroundColor(TD_iPhone[18], 51);
TextDrawFont(TD_iPhone[18], 1);
TextDrawSetProportional(TD_iPhone[18], 1);

TD_iPhone[19] = TextDrawCreate(549.999450, 233.125991, "00:00");
TextDrawLetterSize(TD_iPhone[19], 0.460333, 2.666073);
TextDrawAlignment(TD_iPhone[19], 2);
TextDrawColor(TD_iPhone[19], -1);
TextDrawSetShadow(TD_iPhone[19], 0);
TextDrawSetOutline(TD_iPhone[19], 0);
TextDrawBackgroundColor(TD_iPhone[19], 51);
TextDrawFont(TD_iPhone[19], 2);
TextDrawSetProportional(TD_iPhone[19], 1);

TD_iPhone[20] = TextDrawCreate(549.332702, 254.866653, "1 de enero");
TextDrawLetterSize(TD_iPhone[20], 0.124999, 0.803554);
TextDrawAlignment(TD_iPhone[20], 2);
TextDrawColor(TD_iPhone[20], -1);
TextDrawSetShadow(TD_iPhone[20], 0);
TextDrawSetOutline(TD_iPhone[20], 0);
TextDrawBackgroundColor(TD_iPhone[20], 51);
TextDrawFont(TD_iPhone[20], 1);
TextDrawSetProportional(TD_iPhone[20], 1);

TD_iPhone[21] = TextDrawCreate(549.999572, 342.148040, "Press ~g~Y ~w~to unlock");
TextDrawLetterSize(TD_iPhone[21], 0.257666, 1.276443);
TextDrawAlignment(TD_iPhone[21], 2);
TextDrawColor(TD_iPhone[21], -1);
TextDrawSetShadow(TD_iPhone[21], 0);
TextDrawSetOutline(TD_iPhone[21], 0);
TextDrawBackgroundColor(TD_iPhone[21], 51);
TextDrawFont(TD_iPhone[21], 1);
TextDrawSetProportional(TD_iPhone[21], 1);

TD_iPhone[22] = TextDrawCreate(511.333282, 231.466659, "ld_plan:tvbase");
TextDrawLetterSize(TD_iPhone[22], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[22], 78.666664, 16.177804);
TextDrawAlignment(TD_iPhone[22], 1);
TextDrawColor(TD_iPhone[22], 8388863);
TextDrawSetShadow(TD_iPhone[22], 0);
TextDrawSetOutline(TD_iPhone[22], 0);
TextDrawFont(TD_iPhone[22], 4);

TD_iPhone[23] = TextDrawCreate(511.333282, 231.466705, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[23], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[23], 78.666656, 1.659255);
TextDrawAlignment(TD_iPhone[23], 1);
TextDrawColor(TD_iPhone[23], 16777215);
TextDrawSetShadow(TD_iPhone[23], 0);
TextDrawSetOutline(TD_iPhone[23], 0);
TextDrawFont(TD_iPhone[23], 4);

TD_iPhone[24] = TextDrawCreate(511.333282, 247.814788, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone[24], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[24], 78.666656, 1.659255);
TextDrawAlignment(TD_iPhone[24], 1);
TextDrawColor(TD_iPhone[24], 16777215);
TextDrawSetShadow(TD_iPhone[24], 0);
TextDrawSetOutline(TD_iPhone[24], 0);
TextDrawFont(TD_iPhone[24], 4);

TD_iPhone[25] = TextDrawCreate(511.666900, 344.296508, "ld_plan:tvbase");
TextDrawLetterSize(TD_iPhone[25], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone[25], 78.333389, 33.185237);
TextDrawAlignment(TD_iPhone[25], 1);
TextDrawColor(TD_iPhone[25], -1);
TextDrawSetShadow(TD_iPhone[25], 0);
TextDrawSetOutline(TD_iPhone[25], 0);
TextDrawFont(TD_iPhone[25], 4);

//Clock
TD_iPhone_Clock[0] = TextDrawCreate(549.633178, 252.551788, "00:00");
TextDrawLetterSize(TD_iPhone_Clock[0], 0.499667, 2.861037);
TextDrawAlignment(TD_iPhone_Clock[0], 2);
TextDrawColor(TD_iPhone_Clock[0], -1);
TextDrawSetShadow(TD_iPhone_Clock[0], 0);
TextDrawSetOutline(TD_iPhone_Clock[0], 0);
TextDrawBackgroundColor(TD_iPhone_Clock[0], 51);
TextDrawFont(TD_iPhone_Clock[0], 2);
TextDrawSetProportional(TD_iPhone_Clock[0], 1);

TD_iPhone_Clock[1] = TextDrawCreate(549.066528, 277.052032, "1 of enero of 1999");
TextDrawLetterSize(TD_iPhone_Clock[1], 0.124999, 0.803554);
TextDrawAlignment(TD_iPhone_Clock[1], 2);
TextDrawColor(TD_iPhone_Clock[1], -1);
TextDrawSetShadow(TD_iPhone_Clock[1], 0);
TextDrawSetOutline(TD_iPhone_Clock[1], 0);
TextDrawBackgroundColor(TD_iPhone_Clock[1], 51);
TextDrawFont(TD_iPhone_Clock[1], 1);
TextDrawSetProportional(TD_iPhone_Clock[1], 1);

//Galeria
TD_iPhone_Gallery = TextDrawCreate(542.000122, 340.977722, "~<~_Sin titulo.png_~>~");
TextDrawLetterSize(TD_iPhone_Gallery, 0.202333, 1.069037);
TextDrawAlignment(TD_iPhone_Gallery, 2);
TextDrawColor(TD_iPhone_Gallery, -1);
TextDrawSetShadow(TD_iPhone_Gallery, 0);
TextDrawSetOutline(TD_iPhone_Gallery, 1);
TextDrawBackgroundColor(TD_iPhone_Gallery, 255);
TextDrawFont(TD_iPhone_Gallery, 1);
TextDrawSetProportional(TD_iPhone_Gallery, 1);

//Clima
TD_iPhone_Time[0] = TextDrawCreate(582.999938, 335.585296, "Sunny");
TextDrawLetterSize(TD_iPhone_Time[0], 0.236999, 0.998518);
TextDrawAlignment(TD_iPhone_Time[0], 3);
TextDrawColor(TD_iPhone_Time[0], -1);
TextDrawSetShadow(TD_iPhone_Time[0], 0);
TextDrawSetOutline(TD_iPhone_Time[0], 1);
TextDrawBackgroundColor(TD_iPhone_Time[0], 255);
TextDrawFont(TD_iPhone_Time[0], 1);
TextDrawSetProportional(TD_iPhone_Time[0], 1);

TD_iPhone_Time[1] = TextDrawCreate(518.333312, 258.844390, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone_Time[1], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone_Time[1], 64.666687, 72.177795);
TextDrawAlignment(TD_iPhone_Time[1], 1);
TextDrawColor(TD_iPhone_Time[1], -1);
TextDrawSetShadow(TD_iPhone_Time[1], 0);
TextDrawSetOutline(TD_iPhone_Time[1], 0);
TextDrawFont(TD_iPhone_Time[1], 4);

TD_iPhone_Time[2] = TextDrawCreate(555.000000, 323.140777, "wheater.com");
TextDrawLetterSize(TD_iPhone_Time[2], 0.127999, 0.687407);
TextDrawAlignment(TD_iPhone_Time[2], 1);
TextDrawColor(TD_iPhone_Time[2], 255);
TextDrawSetShadow(TD_iPhone_Time[2], 0);
TextDrawSetOutline(TD_iPhone_Time[2], 0);
TextDrawBackgroundColor(TD_iPhone_Time[2], 51);
TextDrawFont(TD_iPhone_Time[2], 1);
TextDrawSetProportional(TD_iPhone_Time[2], 1);

//GPS
TD_iPhone_GPS = TextDrawCreate(547.666870, 253.036956, "You are here:");
TextDrawLetterSize(TD_iPhone_GPS, 0.188666, 0.944592);
TextDrawAlignment(TD_iPhone_GPS, 2);
TextDrawColor(TD_iPhone_GPS, -1);
TextDrawSetShadow(TD_iPhone_GPS, 0);
TextDrawSetOutline(TD_iPhone_GPS, 1);
TextDrawBackgroundColor(TD_iPhone_GPS, 255);
TextDrawFont(TD_iPhone_GPS, 1);
TextDrawSetProportional(TD_iPhone_GPS, 1);

//Radio
TD_iPhone_Radio[0] = TextDrawCreate(542.333251, 258.844360, "~<~ RADIO ~>~");
TextDrawLetterSize(TD_iPhone_Radio[0], 0.265333, 1.085629);
TextDrawAlignment(TD_iPhone_Radio[0], 2);
TextDrawColor(TD_iPhone_Radio[0], -1);
TextDrawSetShadow(TD_iPhone_Radio[0], 0);
TextDrawSetOutline(TD_iPhone_Radio[0], 0);
TextDrawBackgroundColor(TD_iPhone_Radio[0], 51);
TextDrawFont(TD_iPhone_Radio[0], 1);
TextDrawSetProportional(TD_iPhone_Radio[0], 1);

TD_iPhone_Radio[1] = TextDrawCreate(550.999938, 353.592559, "Use ~g~Y~w~ to off");
TextDrawLetterSize(TD_iPhone_Radio[1], 0.227000, 1.006814);
TextDrawAlignment(TD_iPhone_Radio[1], 2);
TextDrawColor(TD_iPhone_Radio[1], -1);
TextDrawSetShadow(TD_iPhone_Radio[1], 0);
TextDrawSetOutline(TD_iPhone_Radio[1], 0);
TextDrawBackgroundColor(TD_iPhone_Radio[1], 51);
TextDrawFont(TD_iPhone_Radio[1], 1);
TextDrawSetProportional(TD_iPhone_Radio[1], 1);

//Musica
TD_iPhone_Music[0] = TextDrawCreate(542.333251, 258.844360, "~<~ MUSIC ~>~");
TextDrawLetterSize(TD_iPhone_Music[0], 0.265333, 1.085629);
TextDrawAlignment(TD_iPhone_Music[0], 2);
TextDrawColor(TD_iPhone_Music[0], -1);
TextDrawSetShadow(TD_iPhone_Music[0], 0);
TextDrawSetOutline(TD_iPhone_Music[0], 0);
TextDrawBackgroundColor(TD_iPhone_Music[0], 51);
TextDrawFont(TD_iPhone_Music[0], 1);
TextDrawSetProportional(TD_iPhone_Music[0], 1);

TD_iPhone_Music[1] = TextDrawCreate(550.999938, 353.592559, "Use ~g~Y~w~ to stop");
TextDrawLetterSize(TD_iPhone_Music[1], 0.227000, 1.006814);
TextDrawAlignment(TD_iPhone_Music[1], 2);
TextDrawColor(TD_iPhone_Music[1], -1);
TextDrawSetShadow(TD_iPhone_Music[1], 0);
TextDrawSetOutline(TD_iPhone_Music[1], 0);
TextDrawBackgroundColor(TD_iPhone_Music[1], 51);
TextDrawFont(TD_iPhone_Music[1], 1);
TextDrawSetProportional(TD_iPhone_Music[1], 1);

//Mapa
TD_iPhone_Map = TextDrawCreate(511.266815, 249.548080, "samaps:map");
TextDrawLetterSize(TD_iPhone_Map, 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone_Map, 78.666656, 126.518585);
TextDrawAlignment(TD_iPhone_Map, 1);
TextDrawColor(TD_iPhone_Map, -1);
TextDrawSetShadow(TD_iPhone_Map, 0);
TextDrawSetOutline(TD_iPhone_Map, 0);
TextDrawFont(TD_iPhone_Map, 4);

//Internet
TD_iPhone_Internet[0] = TextDrawCreate(550.666748, 326.459228, "Service maintenance...~n~Sorry");
TextDrawLetterSize(TD_iPhone_Internet[0], 0.151000, 0.836741);
TextDrawAlignment(TD_iPhone_Internet[0], 2);
TextDrawColor(TD_iPhone_Internet[0], -1);
TextDrawSetShadow(TD_iPhone_Internet[0], 0);
TextDrawSetOutline(TD_iPhone_Internet[0], 1);
TextDrawBackgroundColor(TD_iPhone_Internet[0], 255);
TextDrawFont(TD_iPhone_Internet[0], 1);
TextDrawSetProportional(TD_iPhone_Internet[0], 1);

TD_iPhone_Internet[1] = TextDrawCreate(515.333374, 261.748046, "404");
TextDrawLetterSize(TD_iPhone_Internet[1], 0.858666, 7.237334);
TextDrawAlignment(TD_iPhone_Internet[1], 1);
TextDrawColor(TD_iPhone_Internet[1], -1);
TextDrawSetShadow(TD_iPhone_Internet[1], 0);
TextDrawSetOutline(TD_iPhone_Internet[1], 0);
TextDrawBackgroundColor(TD_iPhone_Internet[1], 51);
TextDrawFont(TD_iPhone_Internet[1], 2);
TextDrawSetProportional(TD_iPhone_Internet[1], 1);

//Calculadora
TD_iPhone_Calculator[0] = TextDrawCreate(522.900268, 354.604370, "0");
TextDrawLetterSize(TD_iPhone_Calculator[0], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[0], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[0], 2);
TextDrawColor(TD_iPhone_Calculator[0], -1);
TextDrawUseBox(TD_iPhone_Calculator[0], true);
TextDrawBoxColor(TD_iPhone_Calculator[0], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[0], 0);
TextDrawSetOutline(TD_iPhone_Calculator[0], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[0], 51);
TextDrawFont(TD_iPhone_Calculator[0], 1);
TextDrawSetProportional(TD_iPhone_Calculator[0], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[0], true);

TD_iPhone_Calculator[1] = TextDrawCreate(549.300354, 354.604370, "=");
TextDrawLetterSize(TD_iPhone_Calculator[1], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[1], 51.000000, 29.037044);
TextDrawAlignment(TD_iPhone_Calculator[1], 2);
TextDrawColor(TD_iPhone_Calculator[1], -1);
TextDrawUseBox(TD_iPhone_Calculator[1], true);
TextDrawBoxColor(TD_iPhone_Calculator[1], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[1], 0);
TextDrawSetOutline(TD_iPhone_Calculator[1], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[1], 51);
TextDrawFont(TD_iPhone_Calculator[1], 1);
TextDrawSetProportional(TD_iPhone_Calculator[1], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[1], true);

TD_iPhone_Calculator[2] = TextDrawCreate(522.900268, 333.204071, "1");
TextDrawLetterSize(TD_iPhone_Calculator[2], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[2], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[2], 2);
TextDrawColor(TD_iPhone_Calculator[2], -1);
TextDrawUseBox(TD_iPhone_Calculator[2], true);
TextDrawBoxColor(TD_iPhone_Calculator[2], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[2], 0);
TextDrawSetOutline(TD_iPhone_Calculator[2], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[2], 51);
TextDrawFont(TD_iPhone_Calculator[2], 1);
TextDrawSetProportional(TD_iPhone_Calculator[2], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[2], true);

TD_iPhone_Calculator[3] = TextDrawCreate(540.233581, 333.204071, "2");
TextDrawLetterSize(TD_iPhone_Calculator[3], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[3], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[3], 2);
TextDrawColor(TD_iPhone_Calculator[3], -1);
TextDrawUseBox(TD_iPhone_Calculator[3], true);
TextDrawBoxColor(TD_iPhone_Calculator[3], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[3], 0);
TextDrawSetOutline(TD_iPhone_Calculator[3], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[3], 51);
TextDrawFont(TD_iPhone_Calculator[3], 1);
TextDrawSetProportional(TD_iPhone_Calculator[3], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[3], true);

TD_iPhone_Calculator[4] = TextDrawCreate(557.900207, 333.204071, "3");
TextDrawLetterSize(TD_iPhone_Calculator[4], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[4], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[4], 2);
TextDrawColor(TD_iPhone_Calculator[4], -1);
TextDrawUseBox(TD_iPhone_Calculator[4], true);
TextDrawBoxColor(TD_iPhone_Calculator[4], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[4], 0);
TextDrawSetOutline(TD_iPhone_Calculator[4], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[4], 51);
TextDrawFont(TD_iPhone_Calculator[4], 1);
TextDrawSetProportional(TD_iPhone_Calculator[4], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[4], true);

TD_iPhone_Calculator[5] = TextDrawCreate(522.900268, 311.803771, "4");
TextDrawLetterSize(TD_iPhone_Calculator[5], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[5], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[5], 2);
TextDrawColor(TD_iPhone_Calculator[5], -1);
TextDrawUseBox(TD_iPhone_Calculator[5], true);
TextDrawBoxColor(TD_iPhone_Calculator[5], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[5], 0);
TextDrawSetOutline(TD_iPhone_Calculator[5], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[5], 51);
TextDrawFont(TD_iPhone_Calculator[5], 1);
TextDrawSetProportional(TD_iPhone_Calculator[5], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[5], true);

TD_iPhone_Calculator[6] = TextDrawCreate(540.233581, 311.803771, "5");
TextDrawLetterSize(TD_iPhone_Calculator[6], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[6], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[6], 2);
TextDrawColor(TD_iPhone_Calculator[6], -1);
TextDrawUseBox(TD_iPhone_Calculator[6], true);
TextDrawBoxColor(TD_iPhone_Calculator[6], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[6], 0);
TextDrawSetOutline(TD_iPhone_Calculator[6], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[6], 51);
TextDrawFont(TD_iPhone_Calculator[6], 1);
TextDrawSetProportional(TD_iPhone_Calculator[6], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[6], true);

TD_iPhone_Calculator[7] = TextDrawCreate(557.900207, 311.803771, "6");
TextDrawLetterSize(TD_iPhone_Calculator[7], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[7], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[7], 2);
TextDrawColor(TD_iPhone_Calculator[7], -1);
TextDrawUseBox(TD_iPhone_Calculator[7], true);
TextDrawBoxColor(TD_iPhone_Calculator[7], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[7], 0);
TextDrawSetOutline(TD_iPhone_Calculator[7], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[7], 51);
TextDrawFont(TD_iPhone_Calculator[7], 1);
TextDrawSetProportional(TD_iPhone_Calculator[7], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[7], true);

TD_iPhone_Calculator[8] = TextDrawCreate(522.900268, 290.403472, "7");
TextDrawLetterSize(TD_iPhone_Calculator[8], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[8], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[8], 2);
TextDrawColor(TD_iPhone_Calculator[8], -1);
TextDrawUseBox(TD_iPhone_Calculator[8], true);
TextDrawBoxColor(TD_iPhone_Calculator[8], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[8], 0);
TextDrawSetOutline(TD_iPhone_Calculator[8], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[8], 51);
TextDrawFont(TD_iPhone_Calculator[8], 1);
TextDrawSetProportional(TD_iPhone_Calculator[8], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[8], true);

TD_iPhone_Calculator[9] = TextDrawCreate(540.233581, 290.403472, "8");
TextDrawLetterSize(TD_iPhone_Calculator[9], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[9], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[9], 2);
TextDrawColor(TD_iPhone_Calculator[9], -1);
TextDrawUseBox(TD_iPhone_Calculator[9], true);
TextDrawBoxColor(TD_iPhone_Calculator[9], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[9], 0);
TextDrawSetOutline(TD_iPhone_Calculator[9], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[9], 51);
TextDrawFont(TD_iPhone_Calculator[9], 1);
TextDrawSetProportional(TD_iPhone_Calculator[9], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[9], true);

TD_iPhone_Calculator[10] = TextDrawCreate(557.900207, 290.403472, "9");
TextDrawLetterSize(TD_iPhone_Calculator[10], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[10], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[10], 2);
TextDrawColor(TD_iPhone_Calculator[10], -1);
TextDrawUseBox(TD_iPhone_Calculator[10], true);
TextDrawBoxColor(TD_iPhone_Calculator[10], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[10], 0);
TextDrawSetOutline(TD_iPhone_Calculator[10], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[10], 51);
TextDrawFont(TD_iPhone_Calculator[10], 1);
TextDrawSetProportional(TD_iPhone_Calculator[10], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[10], true);

TD_iPhone_Calculator[11] = TextDrawCreate(577.899597, 290.403472, "/");
TextDrawLetterSize(TD_iPhone_Calculator[11], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[11], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[11], 2);
TextDrawColor(TD_iPhone_Calculator[11], -1);
TextDrawUseBox(TD_iPhone_Calculator[11], true);
TextDrawBoxColor(TD_iPhone_Calculator[11], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[11], 0);
TextDrawSetOutline(TD_iPhone_Calculator[11], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[11], 51);
TextDrawFont(TD_iPhone_Calculator[11], 1);
TextDrawSetProportional(TD_iPhone_Calculator[11], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[11], true);

TD_iPhone_Calculator[12] = TextDrawCreate(577.899597, 311.803771, "x");
TextDrawLetterSize(TD_iPhone_Calculator[12], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[12], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[12], 2);
TextDrawColor(TD_iPhone_Calculator[12], -1);
TextDrawUseBox(TD_iPhone_Calculator[12], true);
TextDrawBoxColor(TD_iPhone_Calculator[12], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[12], 0);
TextDrawSetOutline(TD_iPhone_Calculator[12], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[12], 51);
TextDrawFont(TD_iPhone_Calculator[12], 1);
TextDrawSetProportional(TD_iPhone_Calculator[12], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[12], true);

TD_iPhone_Calculator[13] = TextDrawCreate(577.899597, 333.204071, "-");
TextDrawLetterSize(TD_iPhone_Calculator[13], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[13], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[13], 2);
TextDrawColor(TD_iPhone_Calculator[13], -1);
TextDrawUseBox(TD_iPhone_Calculator[13], true);
TextDrawBoxColor(TD_iPhone_Calculator[13], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[13], 0);
TextDrawSetOutline(TD_iPhone_Calculator[13], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[13], 51);
TextDrawFont(TD_iPhone_Calculator[13], 1);
TextDrawSetProportional(TD_iPhone_Calculator[13], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[13], true);

TD_iPhone_Calculator[14] = TextDrawCreate(577.899597, 354.604370, "+");
TextDrawLetterSize(TD_iPhone_Calculator[14], 0.271333, 1.359405);
TextDrawTextSize(TD_iPhone_Calculator[14], 10.0, 10.370368);
TextDrawAlignment(TD_iPhone_Calculator[14], 2);
TextDrawColor(TD_iPhone_Calculator[14], -1);
TextDrawUseBox(TD_iPhone_Calculator[14], true);
TextDrawBoxColor(TD_iPhone_Calculator[14], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[14], 0);
TextDrawSetOutline(TD_iPhone_Calculator[14], 0);
TextDrawBackgroundColor(TD_iPhone_Calculator[14], 51);
TextDrawFont(TD_iPhone_Calculator[14], 1);
TextDrawSetProportional(TD_iPhone_Calculator[14], 1);
TextDrawSetSelectable(TD_iPhone_Calculator[14], true);

TD_iPhone_Calculator[15] = TextDrawCreate(516.666625, 255.940597, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone_Calculator[15], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone_Calculator[15], 67.999954, 26.962947);
TextDrawAlignment(TD_iPhone_Calculator[15], 1);
TextDrawColor(TD_iPhone_Calculator[15], -2139062017);
TextDrawSetShadow(TD_iPhone_Calculator[15], 0);
TextDrawSetOutline(TD_iPhone_Calculator[15], 0);
TextDrawFont(TD_iPhone_Calculator[15], 4);

//Call
TD_iPhone_Call[0] = TextDrawCreate(511.333312, 278.755523, "LD_SPAC:white");
TextDrawLetterSize(TD_iPhone_Call[0], 0.000000, 0.000000);
TextDrawTextSize(TD_iPhone_Call[0], 78.333259, 98.725921);
TextDrawAlignment(TD_iPhone_Call[0], 1);
TextDrawColor(TD_iPhone_Call[0], -2041184257);
TextDrawSetShadow(TD_iPhone_Call[0], 0);
TextDrawSetOutline(TD_iPhone_Call[0], 0);
TextDrawFont(TD_iPhone_Call[0], 4);

TD_iPhone_Call[1] = TextDrawCreate(524.999877, 282.488739, "1");
TextDrawLetterSize(TD_iPhone_Call[1], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[1], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[1], 2);
TextDrawColor(TD_iPhone_Call[1], -1);
TextDrawUseBox(TD_iPhone_Call[1], true);
TextDrawBoxColor(TD_iPhone_Call[1], 0);
TextDrawSetShadow(TD_iPhone_Call[1], 0);
TextDrawSetOutline(TD_iPhone_Call[1], 0);
TextDrawBackgroundColor(TD_iPhone_Call[1], 51);
TextDrawFont(TD_iPhone_Call[1], 1);
TextDrawSetProportional(TD_iPhone_Call[1], 1);
TextDrawSetSelectable(TD_iPhone_Call[1], true);

TD_iPhone_Call[2] = TextDrawCreate(549.999328, 282.244262, "2");
TextDrawLetterSize(TD_iPhone_Call[2], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[2], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[2], 2);
TextDrawColor(TD_iPhone_Call[2], -1);
TextDrawUseBox(TD_iPhone_Call[2], true);
TextDrawBoxColor(TD_iPhone_Call[2], 0);
TextDrawSetShadow(TD_iPhone_Call[2], 0);
TextDrawSetOutline(TD_iPhone_Call[2], 0);
TextDrawBackgroundColor(TD_iPhone_Call[2], 51);
TextDrawFont(TD_iPhone_Call[2], 1);
TextDrawSetProportional(TD_iPhone_Call[2], 1);
TextDrawSetSelectable(TD_iPhone_Call[2], true);

TD_iPhone_Call[3] = TextDrawCreate(574.999084, 282.414581, "3");
TextDrawLetterSize(TD_iPhone_Call[3], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[3], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[3], 2);
TextDrawColor(TD_iPhone_Call[3], -1);
TextDrawUseBox(TD_iPhone_Call[3], true);
TextDrawBoxColor(TD_iPhone_Call[3], 0);
TextDrawSetShadow(TD_iPhone_Call[3], 0);
TextDrawSetOutline(TD_iPhone_Call[3], 0);
TextDrawBackgroundColor(TD_iPhone_Call[3], 51);
TextDrawFont(TD_iPhone_Call[3], 1);
TextDrawSetProportional(TD_iPhone_Call[3], 1);
TextDrawSetSelectable(TD_iPhone_Call[3], true);

TD_iPhone_Call[4] = TextDrawCreate(524.999877, 304.229614, "4");
TextDrawLetterSize(TD_iPhone_Call[4], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[4], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[4], 2);
TextDrawColor(TD_iPhone_Call[4], -1);
TextDrawUseBox(TD_iPhone_Call[4], true);
TextDrawBoxColor(TD_iPhone_Call[4], 0);
TextDrawSetShadow(TD_iPhone_Call[4], 0);
TextDrawSetOutline(TD_iPhone_Call[4], 0);
TextDrawBackgroundColor(TD_iPhone_Call[4], 51);
TextDrawFont(TD_iPhone_Call[4], 1);
TextDrawSetProportional(TD_iPhone_Call[4], 1);
TextDrawSetSelectable(TD_iPhone_Call[4], true);

TD_iPhone_Call[5] = TextDrawCreate(549.999328, 304.229614, "5");
TextDrawLetterSize(TD_iPhone_Call[5], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[5], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[5], 2);
TextDrawColor(TD_iPhone_Call[5], -1);
TextDrawUseBox(TD_iPhone_Call[5], true);
TextDrawBoxColor(TD_iPhone_Call[5], 0);
TextDrawSetShadow(TD_iPhone_Call[5], 0);
TextDrawSetOutline(TD_iPhone_Call[5], 0);
TextDrawBackgroundColor(TD_iPhone_Call[5], 51);
TextDrawFont(TD_iPhone_Call[5], 1);
TextDrawSetProportional(TD_iPhone_Call[5], 1);
TextDrawSetSelectable(TD_iPhone_Call[5], true);

TD_iPhone_Call[6] = TextDrawCreate(574.999084, 304.229614, "6");
TextDrawLetterSize(TD_iPhone_Call[6], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[6], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[6], 2);
TextDrawColor(TD_iPhone_Call[6], -1);
TextDrawUseBox(TD_iPhone_Call[6], true);
TextDrawBoxColor(TD_iPhone_Call[6], 0);
TextDrawSetShadow(TD_iPhone_Call[6], 0);
TextDrawSetOutline(TD_iPhone_Call[6], 0);
TextDrawBackgroundColor(TD_iPhone_Call[6], 51);
TextDrawFont(TD_iPhone_Call[6], 1);
TextDrawSetProportional(TD_iPhone_Call[6], 1);
TextDrawSetSelectable(TD_iPhone_Call[6], true);

TD_iPhone_Call[7] = TextDrawCreate(524.999877, 326.800170, "7");
TextDrawLetterSize(TD_iPhone_Call[7], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[7], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[7], 2);
TextDrawColor(TD_iPhone_Call[7], -1);
TextDrawUseBox(TD_iPhone_Call[7], true);
TextDrawBoxColor(TD_iPhone_Call[7], 0);
TextDrawSetShadow(TD_iPhone_Call[7], 0);
TextDrawSetOutline(TD_iPhone_Call[7], 0);
TextDrawBackgroundColor(TD_iPhone_Call[7], 51);
TextDrawFont(TD_iPhone_Call[7], 1);
TextDrawSetProportional(TD_iPhone_Call[7], 1);
TextDrawSetSelectable(TD_iPhone_Call[7], true);

TD_iPhone_Call[8] = TextDrawCreate(549.999328, 326.800170, "8");
TextDrawLetterSize(TD_iPhone_Call[8], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[8], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[8], 2);
TextDrawColor(TD_iPhone_Call[8], -1);
TextDrawUseBox(TD_iPhone_Call[8], true);
TextDrawBoxColor(TD_iPhone_Call[8], 0);
TextDrawSetShadow(TD_iPhone_Call[8], 0);
TextDrawSetOutline(TD_iPhone_Call[8], 0);
TextDrawBackgroundColor(TD_iPhone_Call[8], 51);
TextDrawFont(TD_iPhone_Call[8], 1);
TextDrawSetProportional(TD_iPhone_Call[8], 1);
TextDrawSetSelectable(TD_iPhone_Call[8], true);

TD_iPhone_Call[9] = TextDrawCreate(574.999084, 326.800170, "9");
TextDrawLetterSize(TD_iPhone_Call[9], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[9], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[9], 2);
TextDrawColor(TD_iPhone_Call[9], -1);
TextDrawUseBox(TD_iPhone_Call[9], true);
TextDrawBoxColor(TD_iPhone_Call[9], 0);
TextDrawSetShadow(TD_iPhone_Call[9], 0);
TextDrawSetOutline(TD_iPhone_Call[9], 0);
TextDrawBackgroundColor(TD_iPhone_Call[9], 51);
TextDrawFont(TD_iPhone_Call[9], 1);
TextDrawSetProportional(TD_iPhone_Call[9], 1);
TextDrawSetSelectable(TD_iPhone_Call[9], true);

TD_iPhone_Call[10] = TextDrawCreate(549.999328, 349.370727, "0");
TextDrawLetterSize(TD_iPhone_Call[10], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[10], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[10], 2);
TextDrawColor(TD_iPhone_Call[10], -1);
TextDrawUseBox(TD_iPhone_Call[10], true);
TextDrawBoxColor(TD_iPhone_Call[10], 0);
TextDrawSetShadow(TD_iPhone_Call[10], 0);
TextDrawSetOutline(TD_iPhone_Call[10], 0);
TextDrawBackgroundColor(TD_iPhone_Call[10], 51);
TextDrawFont(TD_iPhone_Call[10], 1);
TextDrawSetProportional(TD_iPhone_Call[10], 1);
TextDrawSetSelectable(TD_iPhone_Call[10], true);

TD_iPhone_Call[11] = TextDrawCreate(524.999877, 349.370727, "C");
TextDrawLetterSize(TD_iPhone_Call[11], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[11], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[11], 2);
TextDrawColor(TD_iPhone_Call[11], -1);
TextDrawUseBox(TD_iPhone_Call[11], true);
TextDrawBoxColor(TD_iPhone_Call[11], 0);
TextDrawSetShadow(TD_iPhone_Call[11], 0);
TextDrawSetOutline(TD_iPhone_Call[11], 0);
TextDrawBackgroundColor(TD_iPhone_Call[11], 51);
TextDrawFont(TD_iPhone_Call[11], 1);
TextDrawSetProportional(TD_iPhone_Call[11], 1);
TextDrawSetSelectable(TD_iPhone_Call[11], true);

TD_iPhone_Call[12] = TextDrawCreate(574.999084, 349.370727, "D");
TextDrawLetterSize(TD_iPhone_Call[12], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_Call[12], 10.0, 22.399999);
TextDrawAlignment(TD_iPhone_Call[12], 2);
TextDrawColor(TD_iPhone_Call[12], -1);
TextDrawUseBox(TD_iPhone_Call[12], true);
TextDrawBoxColor(TD_iPhone_Call[12], 0);
TextDrawSetShadow(TD_iPhone_Call[12], 0);
TextDrawSetOutline(TD_iPhone_Call[12], 0);
TextDrawBackgroundColor(TD_iPhone_Call[12], 51);
TextDrawFont(TD_iPhone_Call[12], 1);
TextDrawSetProportional(TD_iPhone_Call[12], 1);
TextDrawSetSelectable(TD_iPhone_Call[12], true);

//Call YES/NO
TD_iPhone_CallYesNo[0] = TextDrawCreate(534.333129, 320.651794, "N");
TextDrawLetterSize(TD_iPhone_CallYesNo[0], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_CallYesNo[0], 5.000000, 20.325927);
TextDrawAlignment(TD_iPhone_CallYesNo[0], 2);
TextDrawColor(TD_iPhone_CallYesNo[0], -1);
TextDrawUseBox(TD_iPhone_CallYesNo[0], true);
TextDrawBoxColor(TD_iPhone_CallYesNo[0], 2080375039);
TextDrawSetShadow(TD_iPhone_CallYesNo[0], 0);
TextDrawSetOutline(TD_iPhone_CallYesNo[0], 0);
TextDrawBackgroundColor(TD_iPhone_CallYesNo[0], 51);
TextDrawFont(TD_iPhone_CallYesNo[0], 1);
TextDrawSetProportional(TD_iPhone_CallYesNo[0], 1);

TD_iPhone_CallYesNo[1] = TextDrawCreate(563.666198, 320.651794, "Y");
TextDrawLetterSize(TD_iPhone_CallYesNo[1], 0.449999, 1.600000);
TextDrawTextSize(TD_iPhone_CallYesNo[1], 5.000000, 20.325927);
TextDrawAlignment(TD_iPhone_CallYesNo[1], 2);
TextDrawColor(TD_iPhone_CallYesNo[1], -1);
TextDrawUseBox(TD_iPhone_CallYesNo[1], true);
TextDrawBoxColor(TD_iPhone_CallYesNo[1], 8388863);
TextDrawSetShadow(TD_iPhone_CallYesNo[1], 0);
TextDrawSetOutline(TD_iPhone_CallYesNo[1], 0);
TextDrawBackgroundColor(TD_iPhone_CallYesNo[1], 51);
TextDrawFont(TD_iPhone_CallYesNo[1], 1);
TextDrawSetProportional(TD_iPhone_CallYesNo[1], 1);