#if defined __game_system_system_donate_inc
	#endinput
#endif
#define __game_system_system_donate_inc

//közép
#define DONATE_KREDIT		0
#define DONATE_PREMIUMPONT	15
//bal
#define DONATE_KESZPENZ		1
#define DONATE_KOKAIN		2
#define DONATE_HEROIN		3
#define DONATE_MARIHUANA	4
#define DONATE_MATERIAL		5
//jobb
#define DONATE_BORTONIDO	6
#define DONATE_KAMAT		7
#define DONATE_ADO			8
//lent
#define DONATE_FEGYVER		9
#define DONATE_PANCEL		10
#define DONATE_ALAKIT		11
#define DONATE_BELSO		12
#define DONATE_JARMU_SLOT	13
#define DONATE_HAZ_SLOT		14

#define DONATE_LAST		DONATE_PREMIUMPONT

// count
#define DONATE_BUTTONS	(DONATE_LAST+1)